name: Build unblockneteasemusic

on:
  schedule:
    - cron: "0 6 */3 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3

      - name: Build ipk file
        env:
          RELEASE_TYPE: 'release'
        run: |
          pushd .github/sh
          fakeroot bash build-unblockneteasemusic.sh
          echo "ASSET_NAME=$(ls *.ipk)" >> $GITHUB_ENV
          popd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ASSET_NAME }}
          path: .github/sh/*.ipk
          
      - name: Upload Releases
        uses: ncipollo/release-action@v1
        with:
          name: "UnblockNeteaseMusic"
          token: ${{ secrets.workflow_token }}
          allowUpdates: true
          replacesArtifacts: true
          tag: "unblockneteasemusic"
          body: |
            luci-app-unblockneteasemusic for OpemWrt.
          artifacts: ".github/sh/*.ipk"
        
      - name: TG
        run: curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=❤️恭喜主人unblockneteasemusic-${{ matrix.arch }}.ipk编译完成！%0A编译时间：$(TZ='Asia/Shanghai' date +%Y年%m月%d日 %H:%M:%S)%0A下载地址：https://github.com/uixsj/openwrt-ipk/releases/tag/unblockneteasemusic"

