name: Build unblockneteasemusic

on:
  schedule:
    - cron: "0 6 */3 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3

      - name: Build ipk file
        env:
          RELEASE_TYPE: 'release'
        run: |
          pushd .github
          fakeroot bash sh/build-unblockneteasemusic.sh
          echo "ASSET_NAME=$(ls *.ipk)" >> $GITHUB_ENV
          popd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ASSET_NAME }}
          path: .github/*.ipk
          
      - name: Upload Releases
        uses: ncipollo/release-action@v1
        with:
          name: "UnblockNeteaseMusic"
          token: ${{ secrets.workflow_token }}
          allowUpdates: true
          replacesArtifacts: true
          tag: "unblockneteasemusic"
          body: |
            luci-app-unblockneteasemusic for OpemWrt.
          artifacts: ".github/*.ipk"
